version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    ports: 
      - "6379:6379"
  mongo-express:
    image: mongo
    restart: always
    ports:
      - 27017:27017 